import { Poppins } from "next/font/google";


import { VisitorNavbar } from "@/components/_frontpage/Navbar";
import { VisitorFooter } from "@/components/_frontpage/footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
      <main className={`${poppins.variable} antialiased`}>
        
          <VisitorNavbar/>
          <div className="mt-16">
            {children}
          </div>
          <VisitorFooter/>

      </main>
   
  );
}
